-- Production permission catalogue is missing 15 permission rows that the code and seed expect (found in the Step 14 live test).
-- Effect today: Analytics, Campaigns, Navigation Menus, Taxonomy pages and the dashboard Website widget work only for SUPER_ADMIN.
-- This file adds the rows and grants them exactly as prisma/rolePermissionSeed.ts does. Idempotent. NOT applied: review first.
INSERT INTO permissions (id, key, name, module, created_at)
SELECT gen_random_uuid()::text, v.k, v.k, split_part(v.k,'.',1), now() FROM (VALUES ('analytics.read'),('campaigns.archive'),('campaigns.create'),('campaigns.publish'),('campaigns.read'),('campaigns.update'),('industries.manage'),('industries.read'),('navigation_menus.create'),('navigation_menus.delete'),('navigation_menus.publish'),('navigation_menus.read'),('navigation_menus.update'),('product_categories.manage'),('product_categories.read')) v(k)
WHERE NOT EXISTS (SELECT 1 FROM permissions p WHERE p.key = v.k);

INSERT INTO role_permissions (id, role_id, permission_id) SELECT gen_random_uuid()::text, r.id, p.id FROM roles r JOIN permissions p ON p.key IN ('analytics.read','campaigns.archive','campaigns.create','campaigns.publish','campaigns.read','campaigns.update','industries.manage','industries.read','navigation_menus.create','navigation_menus.delete','navigation_menus.publish','navigation_menus.read','navigation_menus.update','product_categories.manage','product_categories.read') WHERE r.key='ADMIN' AND NOT EXISTS (SELECT 1 FROM role_permissions x WHERE x.role_id=r.id AND x.permission_id=p.id);
INSERT INTO role_permissions (id, role_id, permission_id) SELECT gen_random_uuid()::text, r.id, p.id FROM roles r JOIN permissions p ON p.key IN ('analytics.read','campaigns.create','campaigns.publish','campaigns.read','campaigns.update','industries.manage','industries.read','navigation_menus.create','navigation_menus.read','navigation_menus.update','product_categories.manage','product_categories.read') WHERE r.key='MANAGER' AND NOT EXISTS (SELECT 1 FROM role_permissions x WHERE x.role_id=r.id AND x.permission_id=p.id);
INSERT INTO role_permissions (id, role_id, permission_id) SELECT gen_random_uuid()::text, r.id, p.id FROM roles r JOIN permissions p ON p.key IN ('analytics.read','campaigns.create','campaigns.read','industries.read','navigation_menus.create','navigation_menus.read','product_categories.read') WHERE r.key='USER' AND NOT EXISTS (SELECT 1 FROM role_permissions x WHERE x.role_id=r.id AND x.permission_id=p.id);
INSERT INTO role_permissions (id, role_id, permission_id) SELECT gen_random_uuid()::text, r.id, p.id FROM roles r JOIN permissions p ON p.key IN ('analytics.read','campaigns.read','industries.read','navigation_menus.read','product_categories.read') WHERE r.key='VIEWER' AND NOT EXISTS (SELECT 1 FROM role_permissions x WHERE x.role_id=r.id AND x.permission_id=p.id);
INSERT INTO role_permissions (id, role_id, permission_id) SELECT gen_random_uuid()::text, r.id, p.id FROM roles r JOIN permissions p ON p.key IN ('analytics.read','campaigns.archive','campaigns.create','campaigns.publish','campaigns.read','campaigns.update','industries.manage','industries.read','navigation_menus.create','navigation_menus.delete','navigation_menus.publish','navigation_menus.read','navigation_menus.update','product_categories.manage','product_categories.read') WHERE r.key='SUPER_ADMIN' AND NOT EXISTS (SELECT 1 FROM role_permissions x WHERE x.role_id=r.id AND x.permission_id=p.id);
